/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_limbo.gestionar_horarios;

import java.util.Calendar;
import java.util.Date;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author fell
 */
public class PanelIngresarHorario extends javax.swing.JPanel {

    /**
     * Creates new form PanelIngresarHorario
     */
    public PanelIngresarHorario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelar = new javax.swing.JButton();
        ingresar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        volver = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Date date2 = new Date();
        SpinnerDateModel sm2=new SpinnerDateModel(date2, null, null,Calendar.HOUR_OF_DAY);
        horaEntrada = new javax.swing.JSpinner(sm2);
        jLabel2 = new javax.swing.JLabel();
        Date date1 = new Date();
        SpinnerDateModel sm1 =
        new SpinnerDateModel(date1, null, null, Calendar.HOUR_OF_DAY);
        horaSalida = new javax.swing.JSpinner(sm1);
        jLabel3 = new javax.swing.JLabel();
        turno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fechaCreacion = new javax.swing.JTextField(""+new java.sql.Date(Calendar.getInstance().getTime().getTime()));
        jLabel5 = new javax.swing.JLabel();
        comboTurno = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(37, 31, 52));

        cancelar.setText("Cancelar");

        ingresar.setText("Ingresar");
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(20, 218, 226));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Ejemplo: MAÑANA,TARDE");

        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usedPictures/volver.png"))); // NOI18N
        volver.setToolTipText("Volver");
        volver.setActionCommand("Cancelar");

        jPanel1.setBackground(new java.awt.Color(37, 31, 52));
        jPanel1.setLayout(new java.awt.GridLayout(5, 2, 5, 5));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(20, 218, 226));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Hora de entrada");
        jPanel1.add(jLabel1);

        JSpinner.DateEditor de2 = new JSpinner.DateEditor(horaEntrada, "HH:mm");
        horaEntrada.setEditor(de2);
        jPanel1.add(horaEntrada);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(20, 218, 226));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Hora de salida");
        jPanel1.add(jLabel2);

        JSpinner.DateEditor de1 = new JSpinner.DateEditor(horaSalida, "HH:mm");
        horaSalida.setEditor(de1);
        jPanel1.add(horaSalida);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(20, 218, 226));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nombre del turno");
        jPanel1.add(jLabel3);

        turno.setVerifyInputWhenFocusTarget(false);
        turno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                turnoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                turnoFocusLost(evt);
            }
        });
        jPanel1.add(turno);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(20, 218, 226));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Fecha de creación");
        jPanel1.add(jLabel4);

        fechaCreacion.setFocusable(false);
        jPanel1.add(fechaCreacion);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(20, 218, 226));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Activo");
        jPanel1.add(jLabel5);

        comboTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));
        comboTurno.setEnabled(false);
        jPanel1.add(comboTurno);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(252, 252, 252))
            .addGroup(layout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(volver)
                .addContainerGap(561, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(169, 169, 169))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void turnoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_turnoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_turnoFocusGained

    private void turnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_turnoFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_turnoFocusLost

    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton cancelar;
    protected javax.swing.JComboBox<String> comboTurno;
    protected javax.swing.JTextField fechaCreacion;
    protected javax.swing.JSpinner horaEntrada;
    protected javax.swing.JSpinner horaSalida;
    protected javax.swing.JButton ingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    protected javax.swing.JTextField turno;
    protected javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
