/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Tienda.reportes;

import GUI_Tienda.caja.*;
import GUI_Tienda.principal.*;
import GUIingresarProductoFacturaBoleta.*;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author fell
 */
public class OpereacionVenta extends javax.swing.JPanel {

    /**
     * Creates new form ProductoBuscados
     */
    private Color colorDefecto=new Color(255, 255, 204);
    public OpereacionVenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fecha = new javax.swing.JTextField();
        nombreUsuario = new javax.swing.JTextField();
        idVenta = new javax.swing.JTextField();
        precioTotal = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        botonImprimir = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setForeground(new java.awt.Color(255, 255, 0));
        setMaximumSize(new java.awt.Dimension(150, 180));
        setMinimumSize(new java.awt.Dimension(112, 190));
        setName(""); // NOI18N
        setLayout(new java.awt.GridLayout(0, 1));

        fecha.setEditable(false);
        fecha.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        fecha.setForeground(new java.awt.Color(0, 0, 0));
        fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fecha.setText("fecha");
        fecha.setBorder(null);
        fecha.setMaximumSize(new java.awt.Dimension(64, 21));
        fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaActionPerformed(evt);
            }
        });
        add(fecha);

        nombreUsuario.setEditable(false);
        nombreUsuario.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nombreUsuario.setForeground(new java.awt.Color(0, 0, 0));
        nombreUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombreUsuario.setText("nombreUsuario");
        nombreUsuario.setBorder(null);
        nombreUsuario.setMaximumSize(new java.awt.Dimension(64, 21));
        nombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreUsuarioActionPerformed(evt);
            }
        });
        add(nombreUsuario);

        idVenta.setEditable(false);
        idVenta.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        idVenta.setForeground(new java.awt.Color(0, 0, 0));
        idVenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idVenta.setText("idVenta");
        idVenta.setBorder(null);
        idVenta.setMaximumSize(new java.awt.Dimension(64, 21));
        add(idVenta);

        precioTotal.setEditable(false);
        precioTotal.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        precioTotal.setForeground(new java.awt.Color(0, 0, 0));
        precioTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        precioTotal.setText("precioTotal");
        precioTotal.setBorder(null);
        precioTotal.setMaximumSize(new java.awt.Dimension(64, 21));
        add(precioTotal);

        jPanel1.setLayout(new java.awt.GridLayout(1, 3));

        botonImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usedPictures/imprimir.png"))); // NOI18N
        botonImprimir.setActionCommand("botonImprimir");
        botonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonImprimirActionPerformed(evt);
            }
        });
        jPanel1.add(botonImprimir);

        botonModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usedPictures/editar2.png"))); // NOI18N
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });
        jPanel1.add(botonModificar);

        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usedPictures/eliminar.png"))); // NOI18N
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(botonEliminar);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_fechaActionPerformed

    private void nombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreUsuarioActionPerformed

    private void botonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonImprimirActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonModificarActionPerformed
    @Override
    protected void paintComponent(Graphics g) {
           super.paintComponent(g);
           Dimension arcs = new Dimension(16,16); //Border corners arcs {width,height}, change this to whatever you want
           int width = getWidth();
           int height = getHeight();
           Graphics2D graphics = (Graphics2D) g;
           graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);


  
           //Draws the rounded panel with borders.
           graphics.setColor(colorDefecto);//37,31,52
           graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height);//paint background
           graphics.setColor(colorDefecto);
           graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height);//paint border
    };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton botonEliminar;
    protected javax.swing.JButton botonImprimir;
    protected javax.swing.JButton botonModificar;
    protected javax.swing.JTextField fecha;
    protected javax.swing.JTextField idVenta;
    private javax.swing.JPanel jPanel1;
    protected javax.swing.JTextField nombreUsuario;
    protected javax.swing.JTextField precioTotal;
    // End of variables declaration//GEN-END:variables
}
