/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Tienda.reportes;

import GUI_Tienda.principal.*;
import GUIingresarProductoFacturaBoleta.*;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author fell
 */
public class ProductoBuscadosVendido extends javax.swing.JPanel {

    /**
     * Creates new form ProductoBuscados
     */
    private Color colorDefecto=new java.awt.Color(126, 225, 126,70);
    public ProductoBuscadosVendido(boolean isMinimo) {
         if(isMinimo){
            colorDefecto=new java.awt.Color(255, 153, 153,70);
            
        }
        initComponents();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ingresar = new javax.swing.JButton();
        precioSub = new javax.swing.JLabel();
        stock = new javax.swing.JLabel();
        nombreSub = new javax.swing.JLabel();

        setBackground(new java.awt.Color(126, 225, 126));
        setForeground(new java.awt.Color(255, 255, 0));
        setMaximumSize(new java.awt.Dimension(150, 128));
        setMinimumSize(new java.awt.Dimension(150, 128));

        ingresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usedPictures/eliminar.png"))); // NOI18N

        precioSub.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        precioSub.setForeground(new java.awt.Color(255, 255, 255));
        precioSub.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        precioSub.setText("0.0");
        precioSub.setToolTipText("");

        stock.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        stock.setForeground(new java.awt.Color(255, 255, 255));
        stock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stock.setText("0.0");
        stock.setToolTipText("");

        nombreSub.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nombreSub.setForeground(new java.awt.Color(255, 255, 255));
        nombreSub.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreSub.setText("Nombre");
        nombreSub.setToolTipText("");
        nombreSub.setMaximumSize(new java.awt.Dimension(140, 21));
        nombreSub.setMinimumSize(new java.awt.Dimension(140, 21));
        nombreSub.setPreferredSize(new java.awt.Dimension(140, 21));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(precioSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(stock, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(nombreSub, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreSub, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addGap(3, 3, 3)
                .addComponent(precioSub, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(stock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ingresar, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    @Override
    protected void paintComponent(Graphics g) {
           super.paintComponent(g);
           Dimension arcs = new Dimension(16,16); //Border corners arcs {width,height}, change this to whatever you want
           int width = getWidth();
           int height = getHeight();
           Graphics2D graphics = (Graphics2D) g;
           graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);


  
           //Draws the rounded panel with borders.
           graphics.setColor(colorDefecto);//37,31,52
           graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height);//paint background
           graphics.setColor(colorDefecto);
           graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height);//paint border
    };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton ingresar;
    protected javax.swing.JLabel nombreSub;
    protected javax.swing.JLabel precioSub;
    protected javax.swing.JLabel stock;
    // End of variables declaration//GEN-END:variables
}
