/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_limbo.gestionar_usuarios;

import GUI_limbo.gestionar_horarios.*;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JPasswordField;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author fell
 */
public class PanelIngresarUsuario extends javax.swing.JPanel {

    /**
     * Creates new form PanelIngresarHorario
     */
    public PanelIngresarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelar = new javax.swing.JButton();
        ingresar = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombreUsuario = new javax.swing.JTextField();
        con = new javax.swing.JLabel();
        contraseña = new javax.swing.JPasswordField();
        con1 = new javax.swing.JLabel();
        contraseña2 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        rol = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        turno = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        fechaCreacion = new javax.swing.JTextField(""+new java.sql.Date(Calendar.getInstance().getTime().getTime()));
        jLabel5 = new javax.swing.JLabel();
        comboActivo = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(37, 31, 52));

        cancelar.setText("Cancelar");

        ingresar.setText("Ingresar");
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });

        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usedPictures/volver.png"))); // NOI18N
        volver.setToolTipText("Volver");
        volver.setActionCommand("Cancelar");

        jPanel1.setBackground(new java.awt.Color(37, 31, 52));
        jPanel1.setLayout(new java.awt.GridLayout(7, 2, 5, 5));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(20, 218, 226));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nombre de usuario");
        jPanel1.add(jLabel1);
        jPanel1.add(nombreUsuario);

        con.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        con.setForeground(new java.awt.Color(20, 218, 226));
        con.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        con.setText("Contraseña");
        jPanel1.add(con);

        contraseña.setText("jPasswordField1");
        contraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contraseñaKeyReleased(evt);
            }
        });
        jPanel1.add(contraseña);

        con1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        con1.setForeground(new java.awt.Color(20, 218, 226));
        con1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        con1.setText("Confirmar contraseña");
        jPanel1.add(con1);

        contraseña2.setText("jPasswordField1");
        contraseña2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contraseña2KeyReleased(evt);
            }
        });
        jPanel1.add(contraseña2);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(20, 218, 226));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Rol");
        jPanel1.add(jLabel3);

        rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vendedor", "Administrador" }));
        jPanel1.add(rol);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(20, 218, 226));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Turno");
        jPanel1.add(jLabel2);
        jPanel1.add(turno);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(20, 218, 226));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Fecha de creación");
        jPanel1.add(jLabel6);

        fechaCreacion.setEnabled(false);
        fechaCreacion.setVerifyInputWhenFocusTarget(false);
        fechaCreacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fechaCreacionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fechaCreacionFocusLost(evt);
            }
        });
        jPanel1.add(fechaCreacion);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(20, 218, 226));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Activo");
        jPanel1.add(jLabel5);

        comboActivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));
        jPanel1.add(comboActivo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226))
            .addGroup(layout.createSequentialGroup()
                .addGap(425, 425, 425)
                .addComponent(ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(volver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(175, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresarActionPerformed

    private void fechaCreacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fechaCreacionFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaCreacionFocusGained

    private void fechaCreacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fechaCreacionFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaCreacionFocusLost

    private void contraseñaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contraseñaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñaKeyReleased

    private void contraseña2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contraseña2KeyReleased
        // TODO add your handling code here:
        
        String contraseña1=new String(contraseña.getPassword());
        String contraseña3=new String(contraseña2.getPassword());
        if(!contraseña1.equals(contraseña3)){
            contraseña2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "La contraseña no coincide", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 10), new java.awt.Color(255, 102, 51)));
        }
        else{
            contraseña2.setBorder(new JPasswordField().getBorder());
        }
    }//GEN-LAST:event_contraseña2KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton cancelar;
    protected javax.swing.JComboBox<String> comboActivo;
    private javax.swing.JLabel con;
    private javax.swing.JLabel con1;
    protected javax.swing.JPasswordField contraseña;
    protected javax.swing.JPasswordField contraseña2;
    protected javax.swing.JTextField fechaCreacion;
    protected javax.swing.JButton ingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    protected javax.swing.JTextField nombreUsuario;
    protected javax.swing.JComboBox<String> rol;
    protected javax.swing.JComboBox<String> turno;
    protected javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
