/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_limbo.gestionar_usuarios;

import clasesJDBC.ScrollBarCustom;

/**
 *
 * @author fell
 */
public class PanelUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form PanelHorarios
     */
    public PanelUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listHorarios = new javax.swing.JPanel();

        setBackground(new java.awt.Color(37, 31, 52));

        jScrollPane1.setBorder(null);
        jScrollPane1.setVerticalScrollBar(new ScrollBarCustom());

        listHorarios.setBackground(new java.awt.Color(37, 31, 52));
        listHorarios.setMaximumSize(new java.awt.Dimension(545, 778));
        listHorarios.setMinimumSize(new java.awt.Dimension(545, 778));
        listHorarios.setLayout(new java.awt.GridLayout(0, 1, 5, 5));
        jScrollPane1.setViewportView(listHorarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JPanel listHorarios;
    // End of variables declaration//GEN-END:variables
}
