/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Tienda.caja;

import GUI_Tienda.principal.*;
import clasesJDBC.ScrollBarCustom;
import java.awt.event.ActionEvent;

/**
 *
 * @author fell
 */
public class GestionarTiendaCaja extends javax.swing.JPanel {

    private ControladorTiendaCaja pp;
    public GestionarTiendaCaja(ControladorTiendaCaja pp) {
        initComponents();
        this.pp=pp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        egreseIngreso = new javax.swing.JPanel();
        egreso = new javax.swing.JButton();
        ingreso = new javax.swing.JButton();
        ingreso1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        cambioTexto = new javax.swing.JTextField();
        productosSub = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(1100, 620));
        setMinimumSize(new java.awt.Dimension(1100, 620));
        setPreferredSize(new java.awt.Dimension(1100, 620));
        setLayout(new java.awt.GridLayout(1, 0));

        egreseIngreso.setBackground(new java.awt.Color(37, 31, 52));
        egreseIngreso.setMaximumSize(new java.awt.Dimension(591, 662));
        egreseIngreso.setMinimumSize(new java.awt.Dimension(591, 662));

        egreso.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        egreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usedPictures/flujo-de-efectivo.png"))); // NOI18N
        egreso.setText("Egreso");
        egreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                egresoActionPerformed(evt);
            }
        });

        ingreso.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ingreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usedPictures/dinero.png"))); // NOI18N
        ingreso.setText("Ingreso");
        ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoActionPerformed(evt);
            }
        });

        ingreso1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ingreso1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usedPictures/caja.png"))); // NOI18N
        ingreso1.setText("Caja");
        ingreso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingreso1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout egreseIngresoLayout = new javax.swing.GroupLayout(egreseIngreso);
        egreseIngreso.setLayout(egreseIngresoLayout);
        egreseIngresoLayout.setHorizontalGroup(
            egreseIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(egreseIngresoLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(egreseIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ingreso1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(egreso, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(307, Short.MAX_VALUE))
        );
        egreseIngresoLayout.setVerticalGroup(
            egreseIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, egreseIngresoLayout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(egreso)
                .addGap(31, 31, 31)
                .addComponent(ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(ingreso1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        add(egreseIngreso);

        jPanel2.setBackground(new java.awt.Color(37, 31, 52));

        jPanel4.setBackground(new java.awt.Color(37, 31, 52));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        cambioTexto.setBackground(new java.awt.Color(82, 75, 99));
        cambioTexto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cambioTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambioTextoActionPerformed(evt);
            }
        });
        cambioTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cambioTextoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cambioTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 171, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cambioTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        productosSub.setBackground(new java.awt.Color(37, 31, 52));
        productosSub.setAlignmentX(10.0F);
        productosSub.setAlignmentY(10.0F);

        javax.swing.GroupLayout productosSubLayout = new javax.swing.GroupLayout(productosSub);
        productosSub.setLayout(productosSubLayout);
        productosSubLayout.setHorizontalGroup(
            productosSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        productosSubLayout.setVerticalGroup(
            productosSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 110, Short.MAX_VALUE))
                    .addComponent(productosSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productosSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    private void cambioTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambioTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cambioTextoActionPerformed

    private void cambioTextoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cambioTextoKeyReleased
        // TODO add your handling code here:
        int uniqueId =(int) System.currentTimeMillis();
        String commandName = "cambioText";
        ActionEvent event = new ActionEvent(this, uniqueId, commandName);
        pp.actionPerformed(event);
    }//GEN-LAST:event_cambioTextoKeyReleased

    private void egresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_egresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_egresoActionPerformed

    private void ingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoActionPerformed

    private void ingreso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingreso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingreso1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JTextField cambioTexto;
    protected javax.swing.JPanel egreseIngreso;
    protected javax.swing.JButton egreso;
    protected javax.swing.JButton ingreso;
    protected javax.swing.JButton ingreso1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    protected javax.swing.JPanel productosSub;
    // End of variables declaration//GEN-END:variables
}
