/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Tienda.principal;

import GUIingresarProductoFacturaBoleta.*;
import clases.Producto;
import clases.ProductoVendido;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;

/**
 *
 * @author fell
 */
public class PanelProductoVender extends javax.swing.JPanel {

    /**
     * Creates new form PanelProductoIngresar
     */
      private Color colorDefecto=new java.awt.Color(126, 225, 126,70);
    private String mensaje="Cantidad";
    private String mensaje2="Unidad";
    private ControladorTiendaPrincipal pp;
    protected int indice;
    private ProductoVendido producto;
    private ControladorFacturaBoleta controladorFacturaBoleta;
    private String clave;
    public PanelProductoVender(boolean isMinimo,String unidad,ControladorTiendaPrincipal pp,int indice,ProductoVendido producto) {
        this.pp=pp;
        this.producto=producto;
        mensaje=unidad;
        mensaje2=unidad;
        this.indice=indice;
        
        if(isMinimo){
            colorDefecto=new java.awt.Color(255, 153, 153,70);
            mensaje="Bajo stock";
            
        }
        initComponents();
        
        cantidad.setText(""+producto.getCantidadVendida());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cantidad = new javax.swing.JTextField();
        botonEliminar = new javax.swing.JButton();
        precioTotal = new javax.swing.JTextField();
        precioProducto = new javax.swing.JTextField();
        seleccion = new javax.swing.JCheckBox();
        codigoBarras = new javax.swing.JLabel();
        nombreProducto = new javax.swing.JLabel();

        setBackground(new java.awt.Color(37, 31, 52));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(478, 102));
        setMinimumSize(new java.awt.Dimension(478, 102));
        setOpaque(false);

        cantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cantidad.setText("0.0");
        cantidad.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), mensaje, javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 10))); // NOI18N
        cantidad.setMaximumSize(new java.awt.Dimension(75, 80));
        cantidad.setMinimumSize(new java.awt.Dimension(75, 80));
        cantidad.setOpaque(true);
        cantidad.setPreferredSize(new java.awt.Dimension(75, 80));
        cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadActionPerformed(evt);
            }
        });
        cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cantidadKeyReleased(evt);
            }
        });

        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usedPictures/eliminar.png"))); // NOI18N
        botonEliminar.setMaximumSize(new java.awt.Dimension(52, 80));
        botonEliminar.setMinimumSize(new java.awt.Dimension(52, 80));
        botonEliminar.setPreferredSize(new java.awt.Dimension(52, 80));

        precioTotal.setBackground(new java.awt.Color(153, 153, 255));
        precioTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        precioTotal.setText("0.0");
        precioTotal.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "P. Total", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 10))); // NOI18N
        precioTotal.setMaximumSize(new java.awt.Dimension(75, 80));
        precioTotal.setMinimumSize(new java.awt.Dimension(75, 80));
        precioTotal.setPreferredSize(new java.awt.Dimension(75, 80));
        precioTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioTotalActionPerformed(evt);
            }
        });

        precioProducto.setBackground(new java.awt.Color(255, 204, 204));
        precioProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        precioProducto.setText("0.0");
        precioProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Precio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 10))); // NOI18N
        precioProducto.setFocusable(false);
        precioProducto.setMaximumSize(new java.awt.Dimension(75, 80));
        precioProducto.setMinimumSize(new java.awt.Dimension(75, 80));
        precioProducto.setPreferredSize(new java.awt.Dimension(75, 80));
        precioProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioProductoActionPerformed(evt);
            }
        });

        seleccion.setSelected(true);
        seleccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                seleccionMouseReleased(evt);
            }
        });
        seleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionActionPerformed(evt);
            }
        });

        codigoBarras.setBackground(colorDefecto);
        codigoBarras.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        codigoBarras.setForeground(new java.awt.Color(255, 255, 255));
        codigoBarras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigoBarras.setText("000000");

        nombreProducto.setBackground(colorDefecto);
        nombreProducto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        nombreProducto.setForeground(new java.awt.Color(255, 255, 255));
        nombreProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreProducto.setText("Nombre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(codigoBarras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(precioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(precioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seleccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(precioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(precioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(seleccion))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(codigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadActionPerformed

    private void precioTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioTotalActionPerformed

    private void cantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadKeyReleased
        // TODO add your handling code here:
        
        double cantidad=0;

   
        try {
            cantidad=Double.valueOf(this.cantidad.getText());
            pp.getProductosVender().get(""+indice).setCantidadVendida(cantidad);
            ProductoVendido p=pp.getProductosVender().get(""+indice);

           
            String precioTotalunitario=String.format("%.2f",pp.getPrecioVoucher());
            System.out.println("ASDSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS");
            String g=String.format("%.2f",cantidad*producto.getPrecioSalida());
            precioTotal.setText(g);
            pp.getGestionarTiendaPrincipal().totalPrecio.setText(precioTotalunitario);
        } catch (Exception e) {
            System.out.println("ERROR MINIMO");
        }

    }//GEN-LAST:event_cantidadKeyReleased

    private void precioProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioProductoActionPerformed

    private void seleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_seleccionActionPerformed

    private void seleccionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccionMouseReleased
        // TODO add your handling code here:
         int uniqueId =(int) System.currentTimeMillis();
        String commandName = "cambioRecalcular";
        ActionEvent event = new ActionEvent(this, uniqueId, commandName);
        pp.actionPerformed(event);
        if(pp.getGestionarTiendaPrincipal().todosSelected.isSelected()){
           pp.getGestionarTiendaPrincipal().todosSelected.setSelected(false);
        }
    }//GEN-LAST:event_seleccionMouseReleased
    @Override
    protected void paintComponent(Graphics g) {
           super.paintComponent(g);
           Dimension arcs = new Dimension(16,16); //Border corners arcs {width,height}, change this to whatever you want
           int width = getWidth();
           int height = getHeight();
           Graphics2D graphics = (Graphics2D) g;
           graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);


  
           //Draws the rounded panel with borders.
           graphics.setColor(colorDefecto);//37,31,52
           graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height);//paint background
           graphics.setColor(colorDefecto);
           graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height);//paint border
    };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton botonEliminar;
    protected javax.swing.JTextField cantidad;
    protected javax.swing.JLabel codigoBarras;
    protected javax.swing.JLabel nombreProducto;
    protected javax.swing.JTextField precioProducto;
    protected javax.swing.JTextField precioTotal;
    protected javax.swing.JCheckBox seleccion;
    // End of variables declaration//GEN-END:variables
}
