/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Tienda.producto.gestionarProducto;

import GUI_limbo.gestionar_usuarios.*;
import GUI_limbo.gestionar_horarios.*;
import clases.Validator;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JPasswordField;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author fell
 */
public class PanelIngresarProducto extends javax.swing.JPanel {
        
    Validator validador=new Validator();
    /**
     * Creates new form PanelIngresarHorario
     */
    public PanelIngresarProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelar = new javax.swing.JButton();
        ingresar = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        codigoBarras = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nombreProducto = new javax.swing.JTextField();
        con = new javax.swing.JLabel();
        precioVenta = new javax.swing.JTextField();
        con1 = new javax.swing.JLabel();
        precioCompra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        categorias = new javax.swing.JComboBox<>();
        con2 = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        con3 = new javax.swing.JLabel();
        stockMinino = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        unidades = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        fechaCreacion = new javax.swing.JTextField(""+new java.sql.Date(Calendar.getInstance().getTime().getTime()));

        setBackground(new java.awt.Color(37, 31, 52));

        cancelar.setText("Cancelar");
        cancelar.setActionCommand("volver");

        ingresar.setText("Ingresar");
        ingresar.setActionCommand("Ingresar insertar");
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });

        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usedPictures/volver.png"))); // NOI18N
        volver.setToolTipText("Volver");
        volver.setActionCommand("volver");

        jPanel1.setBackground(new java.awt.Color(37, 31, 52));
        jPanel1.setLayout(new java.awt.GridLayout(11, 2, 5, 5));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(20, 218, 226));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Código de barras");
        jPanel1.add(jLabel1);

        codigoBarras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codigoBarrasKeyReleased(evt);
            }
        });
        jPanel1.add(codigoBarras);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(20, 218, 226));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Nombre producto");
        jPanel1.add(jLabel4);
        jPanel1.add(nombreProducto);

        con.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        con.setForeground(new java.awt.Color(20, 218, 226));
        con.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        con.setText("Precio de venta");
        jPanel1.add(con);

        precioVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                precioVentaKeyReleased(evt);
            }
        });
        jPanel1.add(precioVenta);

        con1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        con1.setForeground(new java.awt.Color(20, 218, 226));
        con1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        con1.setText("Precio de compra");
        jPanel1.add(con1);

        precioCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                precioCompraKeyReleased(evt);
            }
        });
        jPanel1.add(precioCompra);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(20, 218, 226));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Categoría");
        jPanel1.add(jLabel3);

        jPanel1.add(categorias);

        con2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        con2.setForeground(new java.awt.Color(20, 218, 226));
        con2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        con2.setText("Stock");
        jPanel1.add(con2);

        cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cantidadKeyReleased(evt);
            }
        });
        jPanel1.add(cantidad);

        con3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        con3.setForeground(new java.awt.Color(20, 218, 226));
        con3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        con3.setText("Stock minimo");
        jPanel1.add(con3);

        stockMinino.setText("0");
        stockMinino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                stockMininoKeyReleased(evt);
            }
        });
        jPanel1.add(stockMinino);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(20, 218, 226));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Unidad de medida");
        jPanel1.add(jLabel2);

        unidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kilogramos", "Unidades", "Litros" }));
        jPanel1.add(unidades);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(20, 218, 226));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Imagen");
        jPanel1.add(jLabel8);

        jButton1.setText("Buscar");
        jButton1.setEnabled(false);
        jPanel1.add(jButton1);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(20, 218, 226));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Fecha de creación");
        jPanel1.add(jLabel9);

        fechaCreacion.setFocusable(false);
        fechaCreacion.setVerifyInputWhenFocusTarget(false);
        fechaCreacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fechaCreacionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fechaCreacionFocusLost(evt);
            }
        });
        jPanel1.add(fechaCreacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(499, 499, 499))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(volver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresarActionPerformed

    private void fechaCreacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fechaCreacionFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaCreacionFocusLost

    private void fechaCreacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fechaCreacionFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaCreacionFocusGained

    private void codigoBarrasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoBarrasKeyReleased
        // TODO add your handling code here:

        if(!validador.validarNumerico(codigoBarras.getText())){

            codigoBarras.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Caracter Incorrecto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 10), new java.awt.Color(255, 102, 51)));
        }
        else{
            codigoBarras.setBorder(new JTextField().getBorder());
        }
    }//GEN-LAST:event_codigoBarrasKeyReleased

    private void precioVentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioVentaKeyReleased
        // TODO add your handling code here:

        if(!validador.validarNumerico(precioVenta.getText())){

            precioVenta.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Caracter Incorrecto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 10), new java.awt.Color(255, 102, 51)));
        }
        else{
            precioVenta.setBorder(new JTextField().getBorder());
        }
        
    }//GEN-LAST:event_precioVentaKeyReleased

    private void precioCompraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioCompraKeyReleased
        // TODO add your handling code here:
        if(!validador.validarNumerico(precioCompra.getText())){

            precioCompra.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Caracter Incorrecto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 10), new java.awt.Color(255, 102, 51)));
        }
        else{
            precioCompra.setBorder(new JTextField().getBorder());
        }
    }//GEN-LAST:event_precioCompraKeyReleased

    private void cantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadKeyReleased
        // TODO add your handling code here:
        if(!validador.validarNumerico(cantidad.getText())){

            cantidad.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Caracter Incorrecto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 10), new java.awt.Color(255, 102, 51)));
        }
        else{
            cantidad.setBorder(new JTextField().getBorder());
        }
    }//GEN-LAST:event_cantidadKeyReleased

    private void stockMininoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stockMininoKeyReleased
        // TODO add your handling code here:
        if(!validador.validarNumerico(stockMinino.getText())){

            stockMinino.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Caracter Incorrecto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 10), new java.awt.Color(255, 102, 51)));
        }
        else{
            stockMinino.setBorder(new JTextField().getBorder());
        }
    }//GEN-LAST:event_stockMininoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton cancelar;
    protected javax.swing.JTextField cantidad;
    protected javax.swing.JComboBox<String> categorias;
    protected javax.swing.JTextField codigoBarras;
    private javax.swing.JLabel con;
    private javax.swing.JLabel con1;
    private javax.swing.JLabel con2;
    private javax.swing.JLabel con3;
    protected javax.swing.JTextField fechaCreacion;
    protected javax.swing.JButton ingresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    protected javax.swing.JTextField nombreProducto;
    protected javax.swing.JTextField precioCompra;
    protected javax.swing.JTextField precioVenta;
    protected javax.swing.JTextField stockMinino;
    protected javax.swing.JComboBox<String> unidades;
    protected javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
