/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIingresarProductoFacturaBoleta;

import clases.Producto;
import clases.ProductoVendido;

/**
 *
 * @author fell
 */
public class PanelProductoIngresar extends javax.swing.JPanel {

    /**
     * Creates new form PanelProductoIngresar
     */
    private ControladorFacturaBoleta controladorFacturaBoleta;
    private String clave;
    public PanelProductoIngresar(String clave,ControladorFacturaBoleta controladorFacturaBoleta) {
        this.clave=clave;
        this.controladorFacturaBoleta=controladorFacturaBoleta;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreProducto = new javax.swing.JLabel();
        codigoBarras = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        botonEliminar = new javax.swing.JButton();
        Total = new javax.swing.JTextField();
        precioProducto = new javax.swing.JTextField();
        precioCompra = new javax.swing.JTextField();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(511, 102));
        setMinimumSize(new java.awt.Dimension(511, 102));

        nombreProducto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        nombreProducto.setText("Producto de prueba");

        codigoBarras.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        codigoBarras.setText("45112");

        cantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cantidad.setText("0.0");
        cantidad.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cantidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 10))); // NOI18N
        cantidad.setMaximumSize(new java.awt.Dimension(75, 80));
        cantidad.setMinimumSize(new java.awt.Dimension(75, 80));
        cantidad.setPreferredSize(new java.awt.Dimension(75, 80));
        cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadActionPerformed(evt);
            }
        });
        cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cantidadKeyReleased(evt);
            }
        });

        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usedPictures/eliminar.png"))); // NOI18N
        botonEliminar.setMaximumSize(new java.awt.Dimension(52, 80));
        botonEliminar.setMinimumSize(new java.awt.Dimension(52, 80));
        botonEliminar.setPreferredSize(new java.awt.Dimension(52, 80));

        Total.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Total.setText("0.0");
        Total.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "P. Total", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 10))); // NOI18N
        Total.setMaximumSize(new java.awt.Dimension(75, 80));
        Total.setMinimumSize(new java.awt.Dimension(75, 80));
        Total.setPreferredSize(new java.awt.Dimension(75, 80));
        Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalActionPerformed(evt);
            }
        });
        Total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TotalKeyReleased(evt);
            }
        });

        precioProducto.setBackground(new java.awt.Color(153, 153, 255));
        precioProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        precioProducto.setText("0.0");
        precioProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "P. venta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 10))); // NOI18N
        precioProducto.setMaximumSize(new java.awt.Dimension(75, 80));
        precioProducto.setMinimumSize(new java.awt.Dimension(75, 80));
        precioProducto.setPreferredSize(new java.awt.Dimension(75, 80));
        precioProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioProductoActionPerformed(evt);
            }
        });
        precioProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                precioProductoKeyReleased(evt);
            }
        });

        precioCompra.setBackground(new java.awt.Color(255, 204, 204));
        precioCompra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        precioCompra.setText("0.0");
        precioCompra.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "P. compra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 10))); // NOI18N
        precioCompra.setFocusable(false);
        precioCompra.setMaximumSize(new java.awt.Dimension(75, 80));
        precioCompra.setMinimumSize(new java.awt.Dimension(75, 80));
        precioCompra.setPreferredSize(new java.awt.Dimension(75, 80));
        precioCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoBarras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(precioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(precioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(codigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(precioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(precioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadActionPerformed

    private void TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalActionPerformed

    private void precioProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioProductoActionPerformed

    private void cantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadKeyReleased
        // TODO add your handling code here:
        
        double cantidad=0;
        double precioSalida=0;
        try {
            cantidad=Double.valueOf(this.cantidad.getText());
            precioSalida=Double.valueOf(this.Total.getText());
            
            String precioTotalunitario=String.format("%.2f",precioSalida/cantidad);
            double precioEntrada=Double.parseDouble(precioTotalunitario);
            controladorFacturaBoleta.getProductosIngresar().get(this.clave).setCantidad(cantidad);
            Producto p=controladorFacturaBoleta.getProductosIngresar().get(clave);

           
            controladorFacturaBoleta.getProductosIngresar().get(clave).setPrecioEntrada(precioEntrada);
            precioCompra.setText(precioTotalunitario);
            System.out.println(" PRECIO SALIDA :"+precioEntrada);
        } catch (Exception e) {
            System.out.println("ERROR MINIMO");
        }

    }//GEN-LAST:event_cantidadKeyReleased

    private void TotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TotalKeyReleased
        // TODO add your handling code here:
        double cantidad=0;
        double entrada=0;
        try {
            cantidad=Double.valueOf(this.cantidad.getText());
            entrada=Double.valueOf(this.Total.getText());
        
                 
            String precioTotalunitario=String.format("%.2f",entrada/cantidad);
            double precioEntrada=Double.parseDouble(precioTotalunitario);
            controladorFacturaBoleta.getProductosIngresar().get(this.clave).setPrecioEntrada(precioEntrada);
            Producto p=controladorFacturaBoleta.getProductosIngresar().get(clave);

           
            controladorFacturaBoleta.getProductosIngresar().get(clave).setPrecioEntrada(precioEntrada);
            precioCompra.setText(precioTotalunitario);
            String precioT=String.format("%.2f",controladorFacturaBoleta.getPrecioVoucher());
            controladorFacturaBoleta.getGestionarTiendaPrincipal().totalPrecio.setText(precioT);
            System.out.println(" PRECIO SALIDA :"+precioTotalunitario);
        } catch (Exception e) {
            System.out.println("ERROR MINIMO");
        }
    }//GEN-LAST:event_TotalKeyReleased

    private void precioCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioCompraActionPerformed

    private void precioProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioProductoKeyReleased
        // TODO add your handling code here:

        double salida=0;
        try {
            salida=Double.valueOf(this.precioProducto.getText());
 
        
                

            controladorFacturaBoleta.getProductosIngresar().get(this.clave).setPrecioSalida(salida);
   

           
         
        } catch (Exception e) {
            System.out.println("ERROR MINIMO");
        }
    }//GEN-LAST:event_precioProductoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JTextField Total;
    protected javax.swing.JButton botonEliminar;
    protected javax.swing.JTextField cantidad;
    protected javax.swing.JLabel codigoBarras;
    public javax.swing.JLabel nombreProducto;
    protected javax.swing.JTextField precioCompra;
    protected javax.swing.JTextField precioProducto;
    // End of variables declaration//GEN-END:variables
}
