/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIingresarProductoFacturaBoleta;
import GUI_Tienda.principal.*;
import clasesJDBC.ScrollBarCustom;
/**
 *
 * @author fell
 */
public class PanelProductosSubFactura extends javax.swing.JPanel {

    /**
     * Creates new form PanelProductosSub
     */
    public PanelProductosSubFactura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelProductosVender1 = new GUI_Tienda.principal.PanelProductosVender();
        jScrollPane7 = new javax.swing.JScrollPane();
        productosSub = new javax.swing.JPanel();

        setBackground(new java.awt.Color(37, 31, 52));

        jScrollPane7.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane7.setBorder(null);
        jScrollPane7.setAlignmentX(10.0F);
        jScrollPane7.setAlignmentY(10.0F);
        jScrollPane7.setFocusCycleRoot(true);
        jScrollPane7.setVerticalScrollBar(new ScrollBarCustom());

        productosSub.setBackground(new java.awt.Color(37, 31, 52));
        productosSub.setAlignmentX(10.0F);
        productosSub.setLayout(new java.awt.GridLayout(0, 3, 2, 10));
        jScrollPane7.setViewportView(productosSub);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane7;
    private GUI_Tienda.principal.PanelProductosVender panelProductosVender1;
    protected javax.swing.JPanel productosSub;
    // End of variables declaration//GEN-END:variables
}
